#!/bin/sh

git_command()
{
	if [ $# != 1 ]; then
		git add . 
		git commit -m "commit"
		git push
	elif [ $# == 1 ]; then
		git add $1
		git commit -m "commit"
		git push
	else
		echo "Usage: up or up < file_name >"
	fi
}

git_command $1
